version: '3'

services:
  coinboot:
    container_name: coinboot
    env_file:
      - ./conf/environment/default.env
    build: ./docker/
    volumes:
      - ./conf/dnsmasq:/etc/dnsmasq.d
      - ./conf/environment/:/srv/environment
      - ./boot:/var/lib/tftpboot
      - ./plugins:/srv/plugins
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
    network_mode: "host"
  mongodb:
    image: mongo:3
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.4
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
        #mem_limit: 1g
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    #image: graylog/graylog:3.0.0-rc.2-2
    image: graylog/graylog:2.5
    environment:
      # CHANGE ME!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_WEB_ENDPOINT_URI=http://192.168.1.2:9000/api
        #- GRAYLOG_REST_LISTEN_URI=http://192.168.1.2:19000/api/
        #- GRAYLOG_REST_TRANSPORT_URI=http://192.168.1.2:19000/api/
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 514:514
      # Syslog UDP
      - 514:514/udp
      # Netconsole raw UDP
      - 5555:5555/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
